---
name: sonarqube_ecocode_javascript

services:
  sonar:
    image: sonarqube:10.7-community
    container_name: sonar_ecocode_javascript
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    depends_on:
      db:
        condition: service_healthy
    environment:
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - type: bind
        source: ./sonar-plugin/target/ecocode-javascript-plugin-1.5.1-SNAPSHOT.jar
        target: /opt/sonarqube/extensions/plugins/ecocode-javascript-plugin-1.5.1-SNAPSHOT.jar
      - "extensions:/opt/sonarqube/extensions"
      - "logs:/opt/sonarqube/logs"
      - "data:/opt/sonarqube/data"
    healthcheck:
      test: wget -qO- http://sonar:9000/api/system/status | grep -q -e '"status":"UP"' -e '"status":"DB_MIGRATION_NEEDED"' -e '"status":"DB_MIGRATION_RUNNING"' || exit 1
      interval: 10s
      timeout: 10s
      retries: 5

  db:
    image: postgres:16-alpine
    container_name: postgresql_ecocode_javascript
    networks:
      - sonarnet
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
      PGDATA: pg_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar -d sonarqube"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  sonarnet:
    driver: bridge

volumes:
  data:
  logs:
  extensions:
  pg_data:
